#nullable enable // autogenerated

using System.Collections.Generic;
using MVZ2.Managers;
using MVZ2Logic.Callbacks;
using MVZ2Logic.Games;
using MVZ2Logic.Inputs;
using UnityEngine;

namespace MVZ2.Inputs
{
    public partial class InputManager : MonoBehaviour, IGlobalInput
    {
        #region 检测指针状态
        public int GetActivePointerType()
        {
            return currentPointerType;
        }
        #endregion

        private void Update()
        {
            UpdatePointer();
            UpdateKeys();
        }

        private void UpdatePointer()
        {
            // Mouse and touch are intentionally polled independently.
            // On iPad a Magic Keyboard/trackpad can be used while fingers are
            // still touching the screen; making the two input paths mutually
            // exclusive drops press/release events and can leave held items stuck.
            PollMousePointerEvents();
            PollTouchPointerEvents();
            FlushPointerCaches();
        }

        private void PollMousePointerEvents()
        {
            if (!Input.mousePresent)
                return;

            var position = (Vector2)Input.mousePosition;
            var delta = mousePositionInitialized ? position - lastMousePosition : Vector2.zero;
            lastMousePosition = position;
            mousePositionInitialized = true;

            var mouseInsideScreen =
                position.x >= 0 && position.y >= 0 &&
                position.x <= Screen.width && position.y <= Screen.height;

            // Moving the pointer without touching the screen is enough to make
            // pointer-sized desktop UI behaviour active again.
            if (mouseInsideScreen && Input.touchCount <= 0 && delta.sqrMagnitude > 0.01f)
            {
                currentPointerType = PointerTypes.MOUSE;
            }

            for (int mouse = 0; mouse <= 2; mouse++)
            {
                bool hasState = false;
                if (Input.GetMouseButtonDown(mouse))
                {
                    hasState = true;
                    currentPointerType = PointerTypes.MOUSE;
                    PollPointerEvent(PointerTypes.MOUSE, mouse, position, delta, PointerPhase.Press);
                }
                if (Input.GetMouseButton(mouse))
                {
                    hasState = true;
                    PollPointerEvent(PointerTypes.MOUSE, mouse, position, delta, PointerPhase.Hold);
                }
                if (Input.GetMouseButtonUp(mouse))
                {
                    hasState = true;
                    currentPointerType = PointerTypes.MOUSE;
                    PollPointerEvent(PointerTypes.MOUSE, mouse, position, delta, PointerPhase.Release);
                }

                // Preserve the original mouse-hover callback behaviour, but do
                // not emit idle mouse events while touch is the active device.
                if (!hasState && currentPointerType == PointerTypes.MOUSE)
                {
                    PollPointerEvent(PointerTypes.MOUSE, mouse, position, delta, PointerPhase.None);
                }
            }
        }

        private void PollTouchPointerEvents()
        {
            int touchCount = Input.touchCount;
            seenTouchIds.Clear();

            for (int i = 0; i < touchCount; i++)
            {
                var touch = Input.GetTouch(i);
                seenTouchIds.Add(touch.fingerId);

                PointerPhase phase = PointerPhase.Hold;
                switch (touch.phase)
                {
                    case TouchPhase.Began:
                        currentPointerType = PointerTypes.TOUCH;
                        phase = PointerPhase.Press;
                        break;
                    case TouchPhase.Moved:
                        currentPointerType = PointerTypes.TOUCH;
                        phase = PointerPhase.Hold;
                        break;
                    case TouchPhase.Ended:
                    case TouchPhase.Canceled:
                        currentPointerType = PointerTypes.TOUCH;
                        phase = PointerPhase.Release;
                        break;
                }

                var delta = Vector2.zero;
                if (lastTouchPositions.TryGetValue(touch.fingerId, out var lastPosition))
                {
                    delta = touch.position - lastPosition;
                }
                lastTouchPositions[touch.fingerId] = touch.position;

                PollPointerEvent(PointerTypes.TOUCH, touch.fingerId, touch.position, delta, phase);

                if (touch.phase == TouchPhase.Ended || touch.phase == TouchPhase.Canceled)
                {
                    lastTouchPositions.Remove(touch.fingerId);
                }
            }

            // Touch indices are not stable when one finger leaves the screen.
            // Keying by fingerId prevents the remaining finger from inheriting
            // another finger's previous position and producing a large false delta.
            if (lastTouchPositions.Count > 0)
            {
                staleTouchIds.Clear();
                foreach (var pair in lastTouchPositions)
                {
                    if (!seenTouchIds.Contains(pair.Key))
                    {
                        staleTouchIds.Add(pair.Key);
                    }
                }
                foreach (var id in staleTouchIds)
                {
                    lastTouchPositions.Remove(id);
                }
            }
        }

        private void FlushPointerCaches()
        {
            foreach (var poll in pointerEventCacheList)
            {
                var param = new LogicCallbacks.PostPointerActionParams()
                {
                    type = poll.type,
                    button = poll.button,
                    screenPos = poll.position,
                    phase = poll.phase,
                    delta = poll.delta,
                };
                Main.Game.RunCallbackFiltered(LogicCallbacks.POST_POINTER_ACTION, param, param.phase);
            }
            pointerEventCacheList.Clear();
        }

        private void PollPointerEvent(int type, int button, Vector2 screenPosition, Vector2 delta, PointerPhase phase)
        {
            var cache = new PointerEventCacheData()
            {
                type = type,
                button = button,
                position = screenPosition,
                phase = phase,
                delta = delta,
            };
            pointerEventCacheList.Add(cache);
        }

        public Vector2 GetPointerScreenPosition()
        {
            return GetPointerScreenPosition(currentPointerType, 0);
        }

        public Vector2 GetPointerScreenPosition(int type, int button)
        {
            return InputHelper.GetPointerPosition(type, button);
        }

        public bool TryGetPointerScreenPosition(out Vector2 screenPosition)
        {
            return TryGetPointerScreenPosition(currentPointerType, 0, out screenPosition);
        }

        public bool TryGetPointerScreenPosition(int type, int button, out Vector2 screenPosition)
        {
            return InputHelper.TryGetPointerPosition(type, button, out screenPosition);
        }

        bool IGlobalInput.IsPointerDown(int type, int button)
        {
            return InputHelper.IsPointerDown(type, button);
        }

        bool IGlobalInput.IsPointerHolding(int type, int button)
        {
            return InputHelper.IsPointerHolding(type, button);
        }

        bool IGlobalInput.IsPointerUp(int type, int button)
        {
            return InputHelper.IsPointerUp(type, button);
        }

        public MainManager Main => MainManager.Instance;

        private int currentPointerType = PointerTypes.MOUSE;
        private Vector2 lastMousePosition;
        private bool mousePositionInitialized;
        private readonly Dictionary<int, Vector2> lastTouchPositions = new Dictionary<int, Vector2>();
        private readonly HashSet<int> seenTouchIds = new HashSet<int>();
        private readonly List<int> staleTouchIds = new List<int>();
        private readonly List<PointerEventCacheData> pointerEventCacheList = new List<PointerEventCacheData>();
    }

    public struct PointerEventCacheData
    {
        public int type;
        public int button;
        public Vector2 position;
        public Vector2 delta;
        public PointerPhase phase;

        public override string ToString()
        {
            return $"type: {type}, button: {button}, position: {position}, delta: {delta}, phase: {phase}";
        }
    }
}
