#nullable enable // autogenerated

using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using MukioI18n;
using MVZ2.Almanacs;
using MVZ2.Audios;
using MVZ2.Cameras;
using MVZ2.Collisions;
using MVZ2.Cursors;
using MVZ2.Debugs;
using MVZ2.GlobalGames;
using MVZ2.Inputs;
using MVZ2.IO;
using MVZ2.Level;
using MVZ2.Level.Components;
using MVZ2.Localization;
using MVZ2.Modding;
using MVZ2.Models;
using MVZ2.Options;
using MVZ2.Saves;
using MVZ2.Scenes;
using MVZ2.Store;
using MVZ2.Supporters;
using MVZ2Logic;
using MVZ2Logic.Definitions;
using MVZ2Logic.Options;
using MVZ2Logic.Resources;
using MVZ2Logic.Serialization;
using PVZEngine;
using PVZEngine.Level;
using UnityEngine;

namespace MVZ2.Managers
{
    public class MainManager : MonoBehaviour
    {
        public async Task Initialize()
        {
            InitGameSettings();
            InitSerializable();
            LogInformations();
            await LoadManagersInit();
            ModManager.PostGameInit();
            initialized = true;
            Scene.Init();
        }
        public void UpdateManagerFixed()
        {
        }
        public bool IsMobile()
        {
#if UNITY_EDITOR
            switch (platformMode)
            {
                case PlatformMode.Mobile:
                    return true;
                case PlatformMode.Standalone:
                    return false;
            }
#endif

#if UNITY_ANDROID || UNITY_IOS
            return true;
#else
            return false;
#endif
        }
        public bool UseMobileLayout()
        {
            if (initialized)
            {
                var screenLayout = OptionsManager.GetScreenLayout();
                if (screenLayout != ScreenLayouts.AUTO)
                {
                    return screenLayout == ScreenLayouts.MOBILE;
                }
            }
            return IsMobile();
        }
        public TaskPipeline? GetLoadPipeline()
        {
            return loadPipeline;
        }
        public Task? GetInitTask()
        {
            return initTask;
        }
        public bool IsFastMode()
        {
#if UNITY_EDITOR
            return fastMode;
#else
            return false;
#endif
        }
        public void InitLoad()
        {
            loadPipeline = new TaskPipeline();
            loadPipeline.AddTask(new PipelineTask(TASK_LOAD_RESOURCES, async (p) =>
            {
                await ResourceManager.LoadAllModResourcesMain(p);
                FontManager.InitFontSprites();
            }));
            loadPipeline.AddTask(new PipelineTask(TASK_LOAD_SPONSORS, (p) => SponsorManager.PullSponsors(p)));

            var task = loadPipeline.Run();
            initTask = task;
            task.ContinueWith((t) =>
            {
                loadPipeline = null;
                initTask = null;
            });
        }

        #region 贴图
        public Sprite? GetFinalSprite(SpriteReference? spriteRef)
        {
            if (!SpriteReference.IsValid(spriteRef))
                return null;
            if (!OptionsManager.HasBloodAndGore())
            {
                var id = spriteRef.ID;
                var censoredId = new NamespaceID(id.SpaceName, $"{id.Path}_censored");
                SpriteReference censoredRef;
                if (spriteRef.IsSheet)
                {
                    censoredRef = new SpriteReference(censoredId, spriteRef.Index);
                }
                else
                {
                    censoredRef = new SpriteReference(censoredId);
                }
                var sprite = LanguageManager.GetCurrentLanguageSprite(censoredRef) ?? ResourceManager.GetSprite(censoredRef);
                if (sprite)
                    return sprite;
            }
            return LanguageManager.GetCurrentLanguageSprite(spriteRef) ?? ResourceManager.GetSprite(spriteRef);
        }
        public Sprite GetFinalSprite(Sprite sprite)
        {
            var spriteID = ResourceManager.GetSpriteReference(sprite);
            if (!SpriteReference.IsValid(spriteID))
                return sprite;
            return GetFinalSprite(spriteID) ?? sprite;
        }
        public Sprite? GetFinalSprite(SpriteReference spriteRef, string language)
        {
            if (!OptionsManager.HasBloodAndGore())
            {
                var id = spriteRef.ID;
                var censoredId = new NamespaceID(id.SpaceName, $"{id.Path}_censored");
                SpriteReference censoredRef;
                if (spriteRef.IsSheet)
                {
                    censoredRef = new SpriteReference(censoredId, spriteRef.Index);
                }
                else
                {
                    censoredRef = new SpriteReference(censoredId);
                }
                var sprite = LanguageManager.GetLocalizedSprite(censoredRef, language) ?? ResourceManager.GetSprite(censoredRef);
                if (sprite)
                    return sprite;
            }
            return LanguageManager.GetLocalizedSprite(spriteRef, language) ?? ResourceManager.GetSprite(spriteRef);
        }
        public Sprite GetFinalSprite(Sprite sprite, string language)
        {
            var spriteID = ResourceManager.GetSpriteReference(sprite);
            if (!SpriteReference.IsValid(spriteID))
                return sprite;
            return GetFinalSprite(spriteID, language) ?? sprite;
        }
        #endregion


        private void Awake()
        {
            if (!Instance)
            {
                Instance = this;
            }
            else
            {
                throw new DuplicateInstanceException(name);
            }
        }
#if UNITY_ANDROID || UNITY_IOS
        private void OnApplicationFocus(bool focus)
        {
            // Mobile OSes can suspend or terminate the process without a normal quit callback.
            if (!focus)
            {
                SaveManager.SaveToFile();
            }
        }

        private void OnApplicationPause(bool pause)
        {
            if (pause)
            {
                SaveManager.SaveToFile();
            }
        }
#endif

        private void OnApplicationQuit()
        {
            SaveManager.SaveToFile(); // 退出游戏后，保存。
        }

        private void InitGameSettings()
        {
            Screen.sleepTimeout = SleepTimeout.NeverSleep;
            TaskScheduler.UnobservedTaskException += TaskScheduler_UnobservedTaskException;
            Input.simulateMouseWithTouches = false;
            Application.SetStackTraceLogType(LogType.Log, StackTraceLogType.None);
            Application.SetStackTraceLogType(LogType.Warning, StackTraceLogType.ScriptOnly);
            Application.SetStackTraceLogType(LogType.Error, StackTraceLogType.Full);

            Game = new GlobalGame(this);
            Global.InitGame(Game);
            ModelFactories.SetFactory(new ModelFactory());

            var levelEngineAssembly = typeof(LevelEngine).Assembly;
            var logicAssembly = typeof(LogicDefinitionTypes).Assembly;
            PropertyMapper.InitPropertyMaps(BuiltinNamespace, levelEngineAssembly.GetTypes());

            Global.Init(new GlobalParams()
            {
                models = new GlobalModels(this),
                almanac = new GlobalAlmanac(this),
                saveData = SaveManager,
                options = OptionsManager,
                input = InputManager,
                level = LevelManager,
                music = MusicManager,
                gui = new GlobalGUI(this),
                scene = Scene,
                localization = LanguageManager,
                debug = DebugManager,
                cursors = CursorManager
            });
        }
        private void InitSerializable()
        {
            SerializeHelper.init(BuiltinNamespace);
            // MVZ2
            SerializeHelper.RegisterClass<SerializableUserDataList>();
            SerializeHelper.RegisterClass<SerializableSaveDataMeta>();
            SerializeHelper.RegisterClass<SerializableAdviceComponent>();
            SerializeHelper.RegisterClass<SerializableArtifactComponent>();
            SerializeHelper.RegisterClass<SerializableLightComponent>();
            SerializeHelper.RegisterClass<SerializableUIComponent>();
            SerializeHelper.RegisterClass<SerializableSoundComponent>();
            SerializeHelper.RegisterClass<SerializableBlueprintComponent>();
            SerializeHelper.RegisterClass<EmptySerializableLevelComponent>();

            SerializeHelper.RegisterClass<SerializableLevelControllerPart>();
            SerializeHelper.RegisterClass<SerializableLevelBlueprintController>();
            SerializeHelper.RegisterClass<SerializableLevelBlueprintChooseController>();

            SerializeHelper.RegisterClass<SerializableBlueprintController>();
            SerializeHelper.RegisterClass<SerializableClassicBlueprintController>();
            SerializeHelper.RegisterClass<SerializableConveyorBlueprintController>();

            SerializeHelper.RegisterClass<SerializableModelData>();
            SerializeHelper.RegisterClass<SerializableSpriteModelData>();
            SerializeHelper.RegisterClass<SerializableUIModelData>();
            SerializeHelper.RegisterClass<SerializableAreaModelData>();

            SerializeHelper.RegisterClass<SerializableModelGroup>();
            SerializeHelper.RegisterClass<SerializableModelGroupArea>();
            SerializeHelper.RegisterClass<SerializableModelGroupEntity>();
            SerializeHelper.RegisterClass<SerializableModelGroupUI>();

            SerializeHelper.RegisterClass<SerializableGraphicElement>();
            SerializeHelper.RegisterClass<SerializableRendererElement>();
            SerializeHelper.RegisterClass<SerializableImageElement>();

            SerializeHelper.RegisterClass<SerializableUnityCollisionSystem>();
            SerializeHelper.RegisterClass<SerializableUnityCollisionEntity>();
            SerializeHelper.RegisterClass<SerializableUnityEntityCollider>();
        }
        private void LogInformations()
        {
            var sb = new StringBuilder();
            sb.AppendLine($"游戏已启动。");
            sb.AppendLine($"应用程序信息：");
            sb.AppendLine($"platform: {Application.platform}");
            sb.AppendLine($"version: {Application.version}");
            sb.AppendLine($"systemLanguage: {Application.systemLanguage}");

            Debug.Log(sb.ToString());
        }
        private async Task LoadManagersInit()
        {
            GraphicsManager.Init();
            FontManager.Init();
            InputManager.InitKeys();
            OptionsManager.InitOptions();

            await ModManager.LoadModInfos(Game);

            // 在MOD信息加载之后
            await ResourceManager.Init();
            await LanguageManager.InitLanguagePacks();

            // 在MOD资源加载之后
            ModManager.InitModLogics(Game);
            ModManager.LoadModLogics(Game);
            ModManager.PostReloadMods(Game);
            OptionsManager.LoadOptions();

            // 在MOD逻辑加载之后
            SaveManager.Load();
            DebugManager.LoadCommandParameterSuggestions();
        }
        private void TaskScheduler_UnobservedTaskException(object sender, UnobservedTaskExceptionEventArgs e)
        {
            if (e.Exception == null)
            {
                Debug.LogError(e);
                return;
            }
            if (e.Exception.InnerException != null)
            {
                Debug.LogError(e.Exception.InnerException);
                return;
            }
            if (e.Exception.InnerExceptions != null)
            {
                foreach (var exception in e.Exception.InnerExceptions)
                {
                    Debug.LogError(exception);
                }
                return;
            }
            Debug.LogError(e.Exception);
        }

        [TranslateMsg("初始化任务名称")]
        public const string TASK_LOAD_RESOURCES = "加载中……";
        [TranslateMsg("初始化任务名称")]
        public const string TASK_LOAD_SPONSORS = "获取赞助者列表……";
        public static MainManager Instance { get; private set; } = null!;
        public GlobalGame Game { get; private set; } = null!;
        public string BuiltinNamespace => builtinNamespace;
        public CoroutineManager CoroutineManager => coroutine;
        public ResourceManager ResourceManager => resource;
        public ModelManager ModelManager => model;
        public SoundManager SoundManager => sound;
        public MusicManager MusicManager => music;
        public LevelManager LevelManager => level;
        public LanguageManager LanguageManager => lang;
        public SaveManager SaveManager => save;
        public ModManager ModManager => mod;
        public CursorManager CursorManager => cursor;
        public ShakeManager ShakeManager => shake;
        public FileManager FileManager => file;
        public FontManager FontManager => fontManager;
        public OptionsManager OptionsManager => options;
        public ResolutionManager ResolutionManager => resolution;
        public SceneLoadingManager SceneManager => sceneLoadingManager;
        public AlmanacManager AlmanacManager => almanacManager;
        public StoreManager StoreManager => storeManager;
        public InputManager InputManager => inputManager;
        public SponsorManager SponsorManager => sponsorManager;
        public GraphicsManager GraphicsManager => graphicsManager;
        public DebugManager DebugManager => debugManager;
        public MainSceneController Scene => scene;
        public PerformanceManager PerformanceManager => performanceManager;
        public TalkManager TalkManager => talkManager;

        private Task? initTask;
        private TaskPipeline? loadPipeline;
        private bool initialized = false;

        [SerializeField]
        private string builtinNamespace = "mvz2";
#if UNITY_EDITOR
        [SerializeField]
        private PlatformMode platformMode = PlatformMode.Default;
#endif
        [SerializeField]
        private bool fastMode;
        [SerializeField]
        private CoroutineManager coroutine = null!;
        [SerializeField]
        private ResourceManager resource = null!;
        [SerializeField]
        private ModelManager model = null!;
        [SerializeField]
        private SoundManager sound = null!;
        [SerializeField]
        private MusicManager music = null!;
        [SerializeField]
        private LevelManager level = null!;
        [SerializeField]
        private LanguageManager lang = null!;
        [SerializeField]
        private SaveManager save = null!;
        [SerializeField]
        private ModManager mod = null!;
        [SerializeField]
        private CursorManager cursor = null!;
        [SerializeField]
        private ShakeManager shake = null!;
        [SerializeField]
        private FileManager file = null!;
        [SerializeField]
        private FontManager fontManager = null!;
        [SerializeField]
        private OptionsManager options = null!;
        [SerializeField]
        private ResolutionManager resolution = null!;
        [SerializeField]
        private SceneLoadingManager sceneLoadingManager = null!;
        [SerializeField]
        private AlmanacManager almanacManager = null!;
        [SerializeField]
        private StoreManager storeManager = null!;
        [SerializeField]
        private InputManager inputManager = null!;
        [SerializeField]
        private SponsorManager sponsorManager = null!;
        [SerializeField]
        private GraphicsManager graphicsManager = null!;
        [SerializeField]
        private DebugManager debugManager = null!;
        [SerializeField]
        private PerformanceManager performanceManager = null!;
        [SerializeField]
        private TalkManager talkManager = null!;
        [SerializeField]
        private MainSceneController scene = null!;
        public enum PlatformMode
        {
            Default,
            Mobile,
            Standalone
        }
    }
    public class DuplicateInstanceException : Exception
    {
        public DuplicateInstanceException(string instanceName) : base($"There's already an instance of {instanceName} in the game.")
        {

        }

        public DuplicateInstanceException() : base()
        {
        }

        public DuplicateInstanceException(string message, Exception innerException) : base(message, innerException)
        {
        }
    }
    public class TaskPipeline
    {
        public async Task Run()
        {
            SetCurrentTask(0);
            for (int i = 0; i < tasks.Count; i++)
            {
                var task = tasks[i];
                await task.Run();
                SetCurrentTask(i + 1);
            }
        }
        public void AddTask(PipelineTask child)
        {
            tasks.Add(child);
        }
        public void RemoveTask(PipelineTask child)
        {
            tasks.Remove(child);
        }
        public void SetCurrentTask(int index)
        {
            currentTaskIndex = index;
        }
        public bool IsFinished()
        {
            return currentTaskIndex >= tasks.Count;
        }
        public string GetCurrentTaskName()
        {
            var task = GetCurrentTask();
            if (task == null)
                return string.Empty;
            return task.GetName();
        }
        public string? GetCurrentProgressName()
        {
            var task = GetCurrentTask();
            if (task == null)
                return string.Empty;
            return task.GetProgressName();
        }
        public float GetProgress()
        {
            if (tasks.Count > 0)
            {
                return tasks.Sum(c => c.GetProgress()) / tasks.Count;
            }
            return 1;
        }
        private PipelineTask? GetCurrentTask()
        {
            if (currentTaskIndex < 0 || currentTaskIndex >= tasks.Count)
                return null;
            return tasks[currentTaskIndex];
        }
        private int currentTaskIndex;
        private List<PipelineTask> tasks = new List<PipelineTask>();
        private float progress;
    }
    public delegate Task TaskAction(TaskProgress progress);
    public class PipelineTask
    {
        public PipelineTask(string name, TaskAction action) : this(name, action, new TaskProgress())
        {
        }
        public PipelineTask(string name, TaskAction action, TaskProgress progress)
        {
            this.name = name;
            this.action = action;
            this.progress = progress;
        }
        public float GetProgress()
        {
            return progress.GetProgress();
        }
        public Task Run()
        {
            if (action == null)
                return Task.CompletedTask;
            return action.Invoke(progress);
        }
        public string GetName()
        {
            return name;
        }
        public string? GetProgressName()
        {
            return progress.GetCurrentTaskName();
        }
        private string name;
        private TaskProgress progress;
        private TaskAction action;
    }
    public class TaskProgress
    {
        public TaskProgress()
        {
        }
        public TaskProgress AddChild()
        {
            var progress = new TaskProgress();
            children.Add(progress);
            return progress;
        }
        public TaskProgress[] AddChildren(int count)
        {
            var array = new TaskProgress[count];
            for (int i = 0; i < count; i++)
            {
                array[i] = AddChild();
            }
            return array;
        }
        public float GetProgress()
        {
            if (children.Count > 0)
            {
                return children.Sum(c => c.GetProgress()) / children.Count;
            }
            return progress;
        }
        public void SetProgress(float progress)
        {
            this.progress = progress;
        }
        public void SetProgress(float progress, string taskName)
        {
            SetProgress(progress);
            SetCurrentTaskName(taskName);
        }
        public string? GetCurrentTaskName()
        {
            if (children.Count > 0)
            {
                var name = children.Where(c => c.progress < 1).Select(e => e.GetCurrentTaskName()).FirstOrDefault(c => !string.IsNullOrEmpty(c));
                if (!string.IsNullOrEmpty(taskName))
                {
                    if (string.IsNullOrEmpty(name))
                        return $"{taskName}/";
                    else
                        return $"{taskName}/{name}";
                }
                else
                {
                    if (string.IsNullOrEmpty(name))
                        return string.Empty;
                    else
                        return name;
                }
            }
            return taskName;
        }
        public void SetCurrentTaskName(string name)
        {
            this.taskName = name;
        }
        private float progress;
        private string? taskName;
        private List<TaskProgress> children = new List<TaskProgress>();
    }
}
